DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    /*title TEXT NOT NULL,
    body TEXT NOT NULL,*/
    number1 INTEGER NOT NULL,
    number2 INTEGER NOT NULL,
    number3 INTEGER NOT NULL,
    number4 INTEGER NOT NULL,
    number5 INTEGER NOT NULL,
    number6 INTEGER NOT NULL,
    number7 INTEGER NOT NULL,
    number8 INTEGER NOT NULL,
    number9 INTEGER NOT NULL,
    number10 INTEGER NOT NULL,
    number11 INTEGER NOT NULL,
    number12 INTEGER NOT NULL,
    number13 INTEGER NOT NULL,
    number14 INTEGER NOT NULL,
    number15 INTEGER NOT NULL,
    number16 INTEGER NOT NULL,
    number17 INTEGER NOT NULL,
    number18 INTEGER NOT NULL,
    number19 INTEGER NOT NULL,
    number20 INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);